name: Build and Release LaTeX document

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_release_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Résumé.tex
          latexmk_use_xelatex: true
          pre_compile: |
              apk add msttcorefonts-installer fontconfig
              update-ms-fonts
              fc-cache -f
          
      - name: Stash PDF
        run: |
          mv Résumé.pdf $HOME # cache the file
          
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: gh_actions_builds
          
      - name: Checkout gh_actions_builds Branch
        uses: actions/checkout@v1
        with:
          ref: gh_actions_builds 
          
      - name: Commit PDF
        run: |
          git config --local user.email "984931887@qq.com"
          git config --local user.name "jiashenggu"
          mv $HOME/Résumé.pdf $(pwd) # bring it back 
          git add -f Résumé.pdf
          git commit -m "Updated by GitHub Action Automatically"
          
      - name: Push PDF
        uses: ad-m/github-push-action@master
        with: 
          branch: gh_actions_builds 
          force: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Résumé.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
